# Generated by Django 2.0.13 on 2019-03-19 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Work title')),
                ('iswc', models.CharField(blank=True, max_length=255, verbose_name='International Standard Musical Work Code')),
                ('others_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Work others title')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Metadata provider')),
            ],
        ),
        migrations.CreateModel(
            name='SourceSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_id', models.CharField(blank=True, max_length=255, verbose_name='Metadata provider id')),
                ('single', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='worksingle.Single')),
                ('source', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='worksingle.Source')),
            ],
        ),
        migrations.CreateModel(
            name='WorksSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributors', models.ManyToManyField(related_name='original', to='worksingle.Contributors')),
                ('others_contributors', models.ManyToManyField(related_name='others', to='worksingle.Contributors')),
                ('source', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='worksingle.SourceSingle')),
            ],
        ),
    ]
