# Generated by Django 2.0.13 on 2019-03-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of Contributors')),
            ],
        ),
        migrations.CreateModel(
            name='WorksSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Work title')),
                ('iswc', models.CharField(blank=True, max_length=255, verbose_name='International Standard Musical Work Code')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Metadata provider')),
                ('md_id', models.CharField(blank=True, max_length=255, verbose_name='Metadata provider')),
                ('contributors', models.ManyToManyField(to='users.Contributors')),
            ],
        ),
    ]
