# Generated by mgamez 2.0.13 on 2019-03-19 01:46

from django.db import migrations, models
import pandas as pd


def take_on_me(apps, schema_editor):
    contributor = apps.get_model('users', 'Contributors')
    worksingle = apps.get_model('users', 'WorksSingle')
    a_ha = pd.read_csv('works_metadata.csv')
    a_ha.dropna()
    for i in range(len(a_ha)):
        aux = worksingle.objects.create(
            title=a_ha.iloc[i].loc['title'],
            iswc=a_ha.iloc[i].loc['iswc'],
            source=a_ha.iloc[i].loc['source'],
            md_id=a_ha.iloc[i].loc['id']
        )
        for j in a_ha.iloc[i].loc['contributors'].split('|'):
            aux.contributors.create(name=j)
    return


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contributors_workssingle'),
    ]

    operations = [
            migrations.RunPython(
                take_on_me
        ),
    ]
